server:
  port: 8011
  servlet:
    context-path: /larp
spring:
  web:
    resources:
      static-locations: classpath:/templates/dist/,classpath:/static
#  mvc:
#    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
      enabled: true
  thymeleaf:
    servlet:
      content-type: text/html
    encoding: utf-8
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates/dist/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/LARP?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 12345678
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
file:
  upload: classpath:/static